In [1]:
import pandas as pd

In [3]:
import pandas as pd

movies = pd.read_csv("../data/raw/movies.csv", encoding="latin-1")
ratings = pd.read_csv("../data/raw/ratings.csv", encoding="latin-1")
users = pd.read_csv("../data/raw/users.csv", encoding="latin-1")

In [4]:
print("Movies:", movies.shape)
print("Ratings:", ratings.shape)
print("Users:", users.shape)

Movies: (3883, 3)
Ratings: (1000209, 4)
Users: (6040, 5)

In [5]:
movies.head()

   movie_id                               movie                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [6]:
ratings.head()

   user_id  movie_id  rating  timestamp
0        1      1193       5  978300760
1        1       661       3  978302109
2        1       914       3  978301968
3        1      3408       4  978300275
4        1      2355       5  978824291

In [7]:
users.head()

   user_id gender       age            occupation zip_code
0        1      F  Under 18          K-12 student    48067
1        2      M       56+         self-employed    70072
2        3      M     25-34             scientist    55117
3        4      M     45-49  executive/managerial    02460
4        5      M     25-34                writer    55455

In [8]:
print(movies.columns.tolist())
print(ratings.columns.tolist())
print(users.columns.tolist())

['movie_id', 'movie', 'genres']
['user_id', 'movie_id', 'rating', 'timestamp']
['user_id', 'gender', 'age', 'occupation', 'zip_code']

In [9]:
print(movies.isnull().sum())
print(ratings.isnull().sum())
print(users.isnull().sum())

movie_id    0
movie       0
genres      0
dtype: int64
user_id      0
movie_id     0
rating       0
timestamp    0
dtype: int64
user_id       0
gender        0
age           0
occupation    0
zip_code      0
dtype: int64

In [10]:
print("MOVIES")
print(movies.info())

print("\nRATINGS")
print(ratings.info())

print("\nUSERS")
print(users.info())

MOVIES
<class 'pandas.DataFrame'>
RangeIndex: 3883 entries, 0 to 3882
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  3883 non-null   int64
 1   movie     3883 non-null   str
 2   genres    3883 non-null   str
dtypes: int64(1), str(2)
memory usage: 91.1 KB
None

RATINGS
<class 'pandas.DataFrame'>
RangeIndex: 1000209 entries, 0 to 1000208
Data columns (total 4 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   user_id    1000209 non-null  int64
 1   movie_id   1000209 non-null  int64
 2   rating     1000209 non-null  int64
 3   timestamp  1000209 non-null  int64
dtypes: int64(4)
memory usage: 30.5 MB
None

USERS
<class 'pandas.DataFrame'>
RangeIndex: 6040 entries, 0 to 6039
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     6040 non-null   int64
 1   gender      6040 non-null   str
 2   age         6040 non-null   str
 3   occupation  6040 non-null   str
 4   zip_code    6040 non-null   str
dtypes: int64(1), str(4)
memory usage: 236.1 KB
None

In [11]:
print("Missing values in Movies:")
print(movies.isnull().sum())

print("\nMissing values in Ratings:")
print(ratings.isnull().sum())

print("\nMissing values in Users:")
print(users.isnull().sum())

Missing values in Movies:
movie_id    0
movie       0
genres      0
dtype: int64

Missing values in Ratings:
user_id      0
movie_id     0
rating       0
timestamp    0
dtype: int64

Missing values in Users:
user_id       0
gender        0
age           0
occupation    0
zip_code      0
dtype: int64

In [12]:
print("Duplicate rows in Movies:", movies.duplicated().sum())
print("Duplicate rows in Ratings:", ratings.duplicated().sum())
print("Duplicate rows in Users:", users.duplicated().sum())

Duplicate rows in Movies: 0
Duplicate rows in Ratings: 0
Duplicate rows in Users: 0

In [13]:
print("Movies columns:")
print(movies.columns.tolist())

print("\nRatings columns:")
print(ratings.columns.tolist())

print("\nUsers columns:")
print(users.columns.tolist())

Movies columns:
['movie_id', 'movie', 'genres']

Ratings columns:
['user_id', 'movie_id', 'rating', 'timestamp']

Users columns:
['user_id', 'gender', 'age', 'occupation', 'zip_code']

In [14]:
print("Unique users:", ratings["user_id"].nunique())
print("Unique movies in ratings:", ratings["movie_id"].nunique())
print("Total ratings:", len(ratings))

Unique users: 6040
Unique movies in ratings: 3706
Total ratings: 1000209

In [15]:
total_possible = users["user_id"].nunique() * movies["movie_id"].nunique()
actual_interactions = len(ratings)

sparsity = 1 - (actual_interactions / total_possible)

print("Total possible user-movie interactions:", total_possible)
print("Actual ratings:", actual_interactions)
print("Sparsity:", sparsity)
print("Density:", 1 - sparsity)

Total possible user-movie interactions: 23453320
Actual ratings: 1000209
Sparsity: 0.9573532020200125
Density: 0.042646797979987494

In [16]:
users["user_id"].nunique() * movies["movie_id"].nunique()

23453320

In [17]:
rated_movies = ratings["movie_id"].nunique()

possible_rated_interactions = (
    ratings["user_id"].nunique() * rated_movies
)

sparsity_rated_movies = 1 - (
    len(ratings) / possible_rated_interactions
)

print("Users:", ratings["user_id"].nunique())
print("Movies with ratings:", rated_movies)
print("Possible interactions:", possible_rated_interactions)
print("Actual ratings:", len(ratings))
print("Sparsity:", sparsity_rated_movies)
print("Density:", 1 - sparsity_rated_movies)

Users: 6040
Movies with ratings: 3706
Possible interactions: 22384240
Actual ratings: 1000209
Sparsity: 0.9553163743776871
Density: 0.04468362562231287

In [18]:
print("Ratings per user:")
print(ratings.groupby("user_id").size().describe())

print("\nRatings per movie:")
print(ratings.groupby("movie_id").size().describe())

Ratings per user:
count    6040.000000
mean      165.597517
std       192.747029
min        20.000000
25%        44.000000
50%        96.000000
75%       208.000000
max      2314.000000
dtype: float64

Ratings per movie:
count    3706.000000
mean      269.889099
std       384.047838
min         1.000000
25%        33.000000
50%       123.500000
75%       350.000000
max      3428.000000
dtype: float64

In [19]:
ratings["rating"].value_counts().sort_index()

rating
1     56174
2    107557
3    261197
4    348971
5    226310
Name: count, dtype: int64

In [20]:
ratings["rating"].describe()

count    1.000209e+06
mean     3.581564e+00
std      1.117102e+00
min      1.000000e+00
25%      3.000000e+00
50%      4.000000e+00
75%      4.000000e+00
max      5.000000e+00
Name: rating, dtype: float64

In [21]:
ratings["timestamp"].head()

0    978300760
1    978302109
2    978301968
3    978300275
4    978824291
Name: timestamp, dtype: int64