In [1]:
import pandas as pd

In [3]:
import pandas as pd

movies = pd.read_csv("../data/raw/movies.csv", encoding="latin-1")
ratings = pd.read_csv("../data/raw/ratings.csv", encoding="latin-1")
users = pd.read_csv("../data/raw/users.csv", encoding="latin-1")

In [4]:
print("Movies:", movies.shape)
print("Ratings:", ratings.shape)
print("Users:", users.shape)

Movies: (3883, 3)
Ratings: (1000209, 4)
Users: (6040, 5)

In [5]:
movies.head()

   movie_id                               movie                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [6]:
ratings.head()

   user_id  movie_id  rating  timestamp
0        1      1193       5  978300760
1        1       661       3  978302109
2        1       914       3  978301968
3        1      3408       4  978300275
4        1      2355       5  978824291

In [7]:
users.head()

   user_id gender       age            occupation zip_code
0        1      F  Under 18          K-12 student    48067
1        2      M       56+         self-employed    70072
2        3      M     25-34             scientist    55117
3        4      M     45-49  executive/managerial    02460
4        5      M     25-34                writer    55455

In [8]:
print(movies.columns.tolist())
print(ratings.columns.tolist())
print(users.columns.tolist())

['movie_id', 'movie', 'genres']
['user_id', 'movie_id', 'rating', 'timestamp']
['user_id', 'gender', 'age', 'occupation', 'zip_code']

In [9]:
print(movies.isnull().sum())
print(ratings.isnull().sum())
print(users.isnull().sum())

movie_id    0
movie       0
genres      0
dtype: int64
user_id      0
movie_id     0
rating       0
timestamp    0
dtype: int64
user_id       0
gender        0
age           0
occupation    0
zip_code      0
dtype: int64